const route = require('express').Router();
const userRoute = require('./users');
const officeRoute = require('./offices');
const positionRoute = require('./positions');
const echelonRoute = require('./echelons');
const postRoute = require('./posts');
const postGalleryRoute = require('./post_gallery');
const eventRoute = require('./events');
const pointRoute = require('./points');
const rewardRoute = require('./rewards');
const rewardLogRoute = require('./rewards_logs');
const familyRoute = require('./family');
const provinceRoute = require('./indonesia_provinces');
const cityRoute = require('./indonesia_cities');
const districtRoute = require('./indonesia_districts');
const villageRoute = require('./indonesia_villages');
const userAddressRoute = require('./user_address');
const officeAddressRoute = require('./office_address');
const userPhoneRoute = require('./user_phone');
const familyPhoneRoute = require('./family_phone');
const officePhoneRoute = require('./office_phone');

route.use('/v1/users', userRoute);
route.use('/v1/offices', officeRoute);
route.use('/v1/positions', positionRoute);
route.use('/v1/echelons', echelonRoute);
route.use('/v1/posts', postRoute);
route.use('/v1/post_galleries', postGalleryRoute);
route.use('/v1/events', eventRoute);
route.use('/v1/points', pointRoute);
route.use('/v1/rewards', rewardRoute);
route.use('/v1/reward_logs', rewardLogRoute);
route.use('/v1/families', familyRoute)
route.use('/v1/provinces', provinceRoute);
route.use('/v1/cities', cityRoute);
route.use('/v1/districts', districtRoute);
route.use('/v1/villages', villageRoute);
route.use('/v1/user_addresses', userAddressRoute);
route.use('/v1/office_addresses', officeAddressRoute);
route.use('/v1/user_phones', userPhoneRoute);
route.use('/v1/family_phones', familyPhoneRoute);
route.use('/v1/office_phones', officePhoneRoute);

module.exports = route;