const route = require('express').Router();
const userRoute = require('./users');
const officeRoute = require('./offices');
const positionRoute = require('./positions');
const echelonRoute = require('./echelons');
const postRoute = require('./posts');
const postGalleryRoute = require('./post_gallery');
const eventRoute = require('./events');
const pointRoute = require('./points');
const pointLogRoute = require('./point_logs');
const rewardRoute = require('./rewards');
const rewardLogRoute = require('./rewards_logs');
const familyRoute = require('./family');
const provinceRoute = require('./indonesia_provinces');
const cityRoute = require('./indonesia_cities');
const districtRoute = require('./indonesia_districts');
const villageRoute = require('./indonesia_villages');
const userAddressRoute = require('./user_address');
const familyAddressRoute = require('./family_address');
const officeAddressRoute = require('./office_address');
const userPhoneRoute = require('./user_phone');
const familyPhoneRoute = require('./family_phone');
const officePhoneRoute = require('./office_phone');
const overtimeRoute = require('./overtime');
const absenceRoute = require('./absence');
const attendanceRoute = require('./attendance');
const masterDataRoute = require('./master_data');
const informationRoute = require('./informations');
const employmentStatusRoute = require('./employment_status');
const missionRoute = require('./mission');
const missionGalleryRoute = require('./mission_gallery');
const missionUrlRoute = require('./mission_url');

route.use('/v1/users', userRoute);
route.use('/v1/offices', officeRoute);
route.use('/v1/positions', positionRoute);
route.use('/v1/echelons', echelonRoute);
route.use('/v1/posts', postRoute);
route.use('/v1/post_galleries', postGalleryRoute);
route.use('/v1/events', eventRoute);
route.use('/v1/points', pointRoute);
route.use('/v1/point_logs', pointLogRoute);
route.use('/v1/rewards', rewardRoute);
route.use('/v1/reward_logs', rewardLogRoute);
route.use('/v1/families', familyRoute)
route.use('/v1/provinces', provinceRoute);
route.use('/v1/cities', cityRoute);
route.use('/v1/districts', districtRoute);
route.use('/v1/villages', villageRoute);
route.use('/v1/user_addresses', userAddressRoute);
route.use('/v1/family_addresses', familyAddressRoute);
route.use('/v1/office_addresses', officeAddressRoute);
route.use('/v1/user_phones', userPhoneRoute);
route.use('/v1/family_phones', familyPhoneRoute);
route.use('/v1/office_phones', officePhoneRoute);
route.use('/v1/overtimes', overtimeRoute);
route.use('/v1/absences', absenceRoute);
route.use('/v1/attendances', attendanceRoute);
route.use('/v1/master_data', masterDataRoute);
route.use('/v1/informations', informationRoute);
route.use('/v1/employment_statuses', employmentStatusRoute);
route.use('/v1/missions', missionRoute);
route.use('/v1/mission_galleries', missionGalleryRoute);
route.use('/v1/mission_urls', missionUrlRoute);

module.exports = route;